<a href="https://colab.research.google.com/github/sandesarikeerthi/2303a51635-batch-23/blob/main/lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Generate 4x4 array with random test scores (0-100)
scores = np.random.randint(50, 100, size=(4, 4))
print("Test Scores (4x4 array):\n", scores)
# Row-wise and Column-wise Means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)
# Standard Deviation and Variance
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)
# Global max, min, and their indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)
# Summary
print("\nSummary:")
print(f"Row means: {row_means}")
print(f"Column means: {col_means}")
print(f"Std Dev: {std_dev:.2f}, Variance: {variance:.2f}")
print(f"Max value {global_max} at {max_index}, Min value {global_min} at {min_index}")

Test Scores (4x4 array):
 [[82 81 92 77]
 [62 95 61 66]
 [74 72 72 62]
 [61 94 73 50]]

Row-wise Means: [83.  71.  70.  69.5]
Column-wise Means: [69.75 85.5  74.5  63.75]

Standard Deviation: 12.638606529202498
Variance: 159.734375

Global Max: 95 at index (np.int64(1), np.int64(1))
Global Min: 50 at index (np.int64(3), np.int64(3))

Summary:
Row means: [83.  71.  70.  69.5]
Column means: [69.75 85.5  74.5  63.75]
Std Dev: 12.64, Variance: 159.73
Max value 95 at (np.int64(1), np.int64(1)), Min value 50 at (np.int64(3), np.int64(3))


In [2]:
import numpy as np
# Create a 3x3x3 RGB image array with pixel values 0–255
image = np.random.randint(0, 256, size=(3, 3, 3))
print("Original Image (3x3x3):\n", image)
# Extract Red, Green, Blue channels
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]
print("\nRed Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
# Average intensity per channel
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)
print("\nAverage Intensities:")
print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")
# Brighten image by adding 50 (clip at 255)
brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image (clipped at 255):\n", brightened)

Original Image (3x3x3):
 [[[ 45  14 168]
  [197 114 165]
  [191 166 206]]

 [[181  85 152]
  [  4  49 116]
  [250 136 199]]

 [[ 99 254  27]
  [132  34  27]
  [101 161 126]]]

Red Channel:
 [[ 45 197 191]
 [181   4 250]
 [ 99 132 101]]
Green Channel:
 [[ 14 114 166]
 [ 85  49 136]
 [254  34 161]]
Blue Channel:
 [[168 165 206]
 [152 116 199]
 [ 27  27 126]]

Average Intensities:
Red: 133.33, Green: 112.56, Blue: 131.78

Brightened Image (clipped at 255):
 [[[ 95  64 218]
  [247 164 215]
  [241 216 255]]

 [[231 135 202]
  [ 54  99 166]
  [255 186 249]]

 [[149 255  77]
  [182  84  77]
  [151 211 176]]]
