<a href="https://colab.research.google.com/github/sandesarikeerthi/2303a51635-batch-23/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [67, 74, 81],
    [90, 88, 95],
    [56, 60, 65],
    [82, 79, 84]
])
average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)
selected_students = marks[[1, 3], :]
high_scorers = marks[np.any(marks > 80, axis=1)]
subject_wise = marks.T
print("Average Marks:", average_marks)
print("Minimum Marks:", min_marks)
print("Maximum Marks:", max_marks)
print("Selected Students' Marks:\n", selected_students)
print("Students scoring above 80:\n", high_scorers)
print("Subject-wise Performance:\n", subject_wise)

Average Marks: [85.         74.         91.         60.33333333 81.66666667]
Minimum Marks: [78 67 88 56 79]
Maximum Marks: [92 81 95 65 84]
Selected Students' Marks:
 [[67 74 81]
 [56 60 65]]
Students scoring above 80:
 [[85 78 92]
 [67 74 81]
 [90 88 95]
 [82 79 84]]
Subject-wise Performance:
 [[85 67 90 56 82]
 [78 74 88 60 79]
 [92 81 95 65 84]]


In [2]:
import pandas as pd
data = {
    'Name': ['sai', 'sabir', 'Chandu', 'priya', 'thrishala'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Salary': [48000, 52000, 61000, 45000, 70000]
}
df = pd.DataFrame(data)
high_salary = df[df['Salary'] > 50000]
sorted_df = df.sort_values(by='Salary', ascending=False)
df['Bonus'] = df['Salary'] * 0.10
total_expense = df['Salary'].sum() + df['Bonus'].sum()
df.to_csv('employee_salary_bonus.csv', index=False)
print("Filtered (Salary > 50,000):\n", high_salary)
print("\nSorted by Salary:\n", sorted_df)
print("\nDataFrame with Bonus:\n", df)
print("\nTotal Expense (Salary + Bonus):", total_expense)

Filtered (Salary > 50,000):
         Name   ID Department  Salary
1      sabir  102         IT   52000
2     Chandu  103    Finance   61000
4  thrishala  105  Marketing   70000

Sorted by Salary:
         Name   ID Department  Salary
4  thrishala  105  Marketing   70000
2     Chandu  103    Finance   61000
1      sabir  102         IT   52000
0        sai  101         HR   48000
3      priya  104         IT   45000

DataFrame with Bonus:
         Name   ID Department  Salary   Bonus
0        sai  101         HR   48000  4800.0
1      sabir  102         IT   52000  5200.0
2     Chandu  103    Finance   61000  6100.0
3      priya  104         IT   45000  4500.0
4  thrishala  105  Marketing   70000  7000.0

Total Expense (Salary + Bonus): 303600.0
