<a href="https://colab.research.google.com/github/sandesarikeerthi/2303a51635-batch-23/blob/main/labcode2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
fp = open("example.txt","w")
fp.write("Hello, B.Tech students!\n")
fp.write("This is file handling in python.\n")
fp.write("sr university")
fp.write("keerthi")
fp.close()
print("Data written successfully!")

Data written successfully!


In [3]:
#close file
fp.close()
print("Data written successfully!")

Data written successfully!


In [4]:
#Reading from a file
#open file in read mode
file=open("example.txt","r")


In [5]:
#Read entire content
content = file.read()
print("File Content:\n",content)

File Content:
 Hello, B.Tech students!
Welcome to Python Programming.
This is file handling in python.
sr universitykeerthi


In [6]:
#close file
file.close()

In [7]:
#Reading Line by Line
file = open("example.txt","r")


In [8]:
#Read first line
line1=file.readline()
print("First Line:",line1)


First Line: Hello, B.Tech students!



In [9]:
#read remaining lines
line2=file.readline()
print("Second Line:",line2)

Second Line: Welcome to Python Programming.



In [10]:
line3=file.readline()
print("Line:",line3)
file.close()

Line: This is file handling in python.



In [14]:
#reading All Line into a List
file=open("example.txt","r")
lines=file.readlines()
print("All Lines as List:",lines)
file.close()

All Lines as List: ['Hello, B.Tech students!\n', 'This is file handling in python.\n', 'sr universitykeerthi']


In [15]:
#Appending Data to an Existing File
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()

In [17]:
#using with statement (best practice)
#The with statement automatically closes to
with open("example.txt","r")as fp:
  data=fp.read()
  print(data)

Hello, B.Tech students!
This is file handling in python.
sr universitykeerthiAppending new data...



In [20]:
#working with csv file
import csv
#writing to csv
with open("data.csv","w",newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])

In [21]:
#reading fron csv
with open("data.csv","r")as file:
  re=csv.reader(file)
  for row in re:
    print(row)

['Name', 'Age', 'course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [22]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1DArray:",arr1)

1DArray: [1 2 3 4]


In [23]:
arr2=np.array([[1,2,3,],[4, 5,6]])
print("2DArray:",arr2)

2DArray: [[1 2 3]
 [4 5 6]]


In [24]:
zero_arr=np.zeros((3,3))
print("Zero Array:\n",zero_arr)

Zero Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
ones_arr=np.ones((3,3))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
#range of number
range_arr=np.arange(0,10,2)
#start,stop,step
print("range array:",range_arr)
#Random Array
rand_arr=np.random.rand(3,3)
print("Random array:\n",rand_arr)

range array: [0 2 4 6 8]
Random array:
 [[0.23996807 0.34542632 0.7539581 ]
 [0.47243013 0.24036551 0.86892566]
 [0.92396578 0.99322457 0.12629312]]


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("Dimention:",arr.ndim)
print("Data Type:",arr.dtype)
print("Size:",arr.size)
print("ItemSize:",arr.itemsize)

shape: (2, 3)
Dimention: 2
Data Type: int64
Size: 6
ItemSize: 8


In [32]:
#array indexing and slicing
arr=np.array([10,20,30,40,50])
print("First element:",arr[-1])
print("Last element:",arr[1])
print("slice[1:4]:",arr[1:4])
print("Every second element:",arr[1:2])
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("Element at row 1, col2:",arr2[0,1])
print("second row:",arr2[1,:])
print("second col:",arr2[:,1])

First element: 50
Last element: 20
slice[1:4]: [20 30 40]
Every second element: [20]
Element at row 1, col2: 2
second row: [4 5 6]
second col: [2 5]


In [33]:
#aggregat functions
arr=np.array([[1,2,3],[4,5,6]])
print("sum of all elements:",np.sum(arr))
print("minimum value:",np.min(arr))
print("maximum value:",np.max(arr))
print("mean value:",np.mean(arr))
print("median value:",np.median(arr))
print("standard deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))

sum of all elements: 21
minimum value: 1
maximum value: 6
mean value: 3.5
median value: 3.5
standard deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [34]:
#Mathemaitcal Functions
arr = np.array([1,2,3])
print("sin",np.sin(arr))
print("cos",np.cos(arr))
print("tan",np.tan(arr))
print("log",np.log(arr))
print("exp",np.exp(arr))

sin [0.84147098 0.90929743 0.14112001]
cos [ 0.54030231 -0.41614684 -0.9899925 ]
tan [ 1.55740772 -2.18503986 -0.14254654]
log [0.         0.69314718 1.09861229]
exp [ 2.71828183  7.3890561  20.08553692]


In [36]:
#broadcasting
a=np.array((1,2,3))
b=5
print("Ass scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array((4,5,6))
print("Ass array to array:",c+d)

Ass scalar to array: [6 7 8]
Ass array to array: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
#matrix operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("matrix multipication:\n",np.dot(a,b))
print("transpose:\n",a.T)
print("inverse:\n",np.linalg.inv(a))
print("determinant:\n",np.linalg.det(a))

matrix multipication:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant:
 -2.0000000000000004


In [39]:
#sample program studeent marks
import numpy as np
# Marks of students in 3 subjects
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
